### ISSUE TITLE
Reborn commands on the console dont work [BT]

### ISSUE THREAD

**Issue by vitorsantos98** [mohabhassan/NightFall#13]
Me and Zappa on another day we have try to use the reborn commands on the server console and they dont work, even if you use a remote tool.

commands:
clientkickr 0 "bye"
banid 0
banidr 0 "wh"
dischat 0
distaunt 0

Game version: Medal of Honor Breakthought

**Comment by mohabhassan** [comment]
Hi,
Can you specify which version of Mohaa you're having this issue with and whether or not you're using pre-built nightfall or you built it from scratch?

**Comment by vitorsantos98** [comment]
> 
> 
> Hi,
> Can you specify which version of Mohaa you're having this issue with and whether or not you're using pre-built nightfall or you built it from scratch?

**Comment by vitorsantos98** [comment]
i have reinstall the server and have worked fine now.
