### ISSUE TITLE
API Client request error

### ISSUE THREAD

**Issue by DraGo0oN** [mohabhassan/NightFall#21]
Api client cannot make a request to a ssl url.
Error: ```CA signer not available for verification```

**Comment by mohabhassan** [comment]
Seems like the solution for a similar issue can be found here: https://www.wolfssl.com/forums/post2244.html#p2244
> So in the end I had to define FP_MAX_BITS to 8192, then change the MAX_DH_SZ to 1036 and finally compile SHA-512 enabled (--enable-sha512).

**Comment by mohabhassan** [comment]
upon further research, it seems wolfSSL needs trusted CA file during runtime.
best solution I could come up with: https://curl.se/docs/caextract.html
implementing `curl --remote-name --time-cond cacert.pem https://curl.se/ca/cacert.pem` inside NF
