### ISSUE TITLE
getactiveweap

### ISSUE THREAD

**Issue by vitorsantos98** [mohabhassan/NightFall#32]
I was tryng to get the active weapon on the player hand but is not working even if i have try to change the index to another number.

Platform: Windows 10
Game: Spearhead

This is happening when i have try that:

```
local.weapon = local.attacker getactiveweap 0 (global/stats.scr, 12)
local.weapon = local.attacker ^

^~^~^ Script Error: There are 0 entities with targetname 'DoubleKill'. You are using a command that requires exactly one.

**Comment by mohabhassan** [comment]
Can you try https://github.com/mohabhassan/NightFall/blob/d75047e99ade60cb4e43c15ba975266e19d15344/dgamexwrapper/scripttests/maintt/tests/playermisc.scr#L13 ? It works for me on BT.

**Comment by vitorsantos98** [comment]
Ok so i done the testing and on Reborn this code works fine:

```
local.weapon = local.attacker getactiveweap 0
local.weap_model = local.weapon.model

iprintln ("W1: "  + local.weap_model)

local.weapon = $player[1] getactiveweap 0
local.weap_model = local.weapon.model

iprintln ("W2: "  + local.weap_model)
```

Show both the weapon but on NF on SH this code show this:
```
local.weapon = local.attacker getactiveweap 0 (global/stats.scr, 12)
local.weapon = local.attacker ^

^~^~^ Script Error: There are 0 entities with targetname 'DoubleKill'. You are using a command that requires exactly one.
```
what you getting from kill event on the attacker seems is not a Player entity, is something else
like a player name

**Comment by mohabhassan** [comment]
How do you test damage event ?

**Comment by vitorsantos98** [comment]
when i have created another script for testing this issue, the problem have dissapear.
very weird... so im going to close this issue.
