### ISSUE TITLE
[Feature Request] Send a private message to a specific player from the server

### ISSUE THREAD

**Issue by ysdragon** [mohabhassan/NightFall#45]
New script function like `local.player iprint ""` but replies privately to the player in the message feed.
A clone of `dmmessage` but from server to a specific player.
It can be done via `sayp` rcon command, but a function would be nice.

**Comment by mohabhassan** [comment]
Did you try `stuffsrv "sayone 1 test"`? It should work iirc.

**Comment by eduzappa18** [comment]
No need for a new function, you can do this via script:

```
stuffsrv ("sayp " + (getclientnum local.player) + " test message\n")"
```

**Comment by ysdragon** [comment]
Yes, i know, but i meant a function would nice, like
```c++
local.player sayp "etc"
```
