### ISSUE TITLE
Server asking always the weapon

### ISSUE THREAD

**Issue by vitorsantos98** [mohabhassan/NightFall#7]
Hi!

Today on nightfall i have find this bug making the server to ask a player always the weapon on the roundbased gametype when the roud ends.

To replicate this problem just change the gametype of the server to 3 and kill someone to end the round.

Game: Medal of Honor Spearhead 2.15
Nightfall version: 2.15.V1.1.0

**Comment by doublekill98** [comment]
A update on the bug.

This is happening on the objective gametype too.
